[package]
name = "onedrive_hosts_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
once_cell = "1.18.0"
tokio = { version = "1", features = ["macros"] }
url = "2.4.0"
vercel_runtime = "1.0.2"

[[bin]]
name = "handler"
path = "api/handler.rs"

[lib]
path = "src/lib.rs"
